version: '3.7'

services:
  taskservice:
    image: ghcr.io/maksarts/taskservice:latest
    container_name: taskservice
    depends_on:
      - taskservice_db
    ports:
      - "8080:8080"
    networks:
      core:
        aliases:
          - "taskservice"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://taskservice_db:5432/taskservice_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECURITY_USER=${SECURITY_USER}
      - SECURITY_PASSWORD=${SECURITY_PASSWORD}

  taskservice_db:
    image: postgres:13.3
    container_name: taskservice_db
    environment:
      POSTGRES_DB: "taskservice_db"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./taskservice-data:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready -U admin -d taskservice_db" ]
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2000M
    networks:
      core:
        aliases:
          - "taskservice_db"

networks:
  core:
    driver: bridge