version: '3.7'

services:
  postgres:
    image: postgres:13.3
    container_name: taskservice_db_test
    environment:
      POSTGRES_DB: "taskservice_db_test"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata-test"
    volumes:
      - ./taskservice-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 200M

networks:
  core:
    driver: bridge