version: '3.7'

services:
  taskservicecore:
    image: ghcr.io/maksarts/taskservice:latest
    ports:
      - "8080:8080"
    networks:
      core:
        aliases:
          - "taskservice"

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "taskservice_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - taskservice-data:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready -U admin -d taskservice_db" ]
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2000M
    networks:
      core:
        aliases:
          - "taskservice_db"

networks:
  core:
    driver: bridge