spring:
  main:
    allow-bean-definition-overriding: false
  application:
    name: TaskService
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  security:
    user:
      name: ${SECURITY_USER}
      password: ${SECURITY_PASSWORD}

server:
  port: 8080

springdoc:
  packages-to-scan: ru.maksarts.taskservice
  swagger-ui:
    path: /taskservice-doc
    tryItOutEnabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    filter: true
  api-docs:
    path: /api-docs

taskservice:
  openapi:
    dev-url: http://localhost:8080
  security:
    jwt:
      expiration: 3600000 #  1 h in ms
      cookie-name: jwt-cookie
      refresh-token:
        expiration: 1296000000 # 15 days in ms
        cookie-name: refresh-jwt-cookie
